name: CD

on:
  release:
    types: [published]

jobs:
  publish_stage:
    environment: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up node env and cache node modules
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy github pages
        run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        npm run deploy
