name: CD

on:
  release:
    types: [published]

jobs:
  publish_stage:
    environment: github-pages

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up node env and cache node modules
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy Github pages
        run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        npm run deploy
        echo "Great success! :tada: :point_right: https://tom-si-al.github.io/create-react-app "
