name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up node env and cache node modules
        uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: npm
        run: npm i
      - name: Lint
        run: npm run style
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Unit tests
        run: npm run test

  # Can be refactored to be...
  # - name: Build and test stage
  #   run: |
  #     npm run style
  #     npm run build
  #     npm test
