name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      # TODO: Add lint command
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build command
        run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: npm run test
  # - name: Build and test stage
  #   run: |
  #     TODO: Add lint command
  #     npm run build
  #     npm test

